import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Naveen's | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Header />

     {/* Hero */}

     {/* About */}

     {/* Experience */}

     {/* Skills */}

     {/* Projects */}

     {/* Contact Me */}
    </div>
  );
}
